import CellPhoneNavigation from "@/components/CellPhoneNavigation";
import CopyrightSection from "@/components/CopyrightSection";
import FooterSection from "@/components/FooterSection";
import HeaderComponent from "@/components/HeaderComponent";
import NavigationMenu from "@/components/NavigationMenu";
import type { Metadata } from "next";

import "./globals.css";
import CurrencyInitializer from "@/components/CurrencyInitializer";
import Providers from "@/providers/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <CurrencyInitializer />
          <HeaderComponent />
          <NavigationMenu />
          {children}
          <FooterSection />
          <CopyrightSection />
          <CellPhoneNavigation />
        </Providers>
      </body>
    </html>
  );
}
