import type { Metadata } from "next";
import "./globals.css";

import Providers from "@/providers/Providers";
import RootLayoutContent from "@/components/layouts/RootLayoutContent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="roboto">
        <Providers>
          <RootLayoutContent>{children}</RootLayoutContent>
        </Providers>
      </body>
    </html>
  );
}
