import { notFound } from 'next/navigation';

import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';

import RootLayoutContent from '@/components/layouts/RootLayoutContent';

import { TypeLocales, routing } from '@/i18n/routing';
import { hasLocale } from '@/i18n/utils';
import Providers from '@/providers/Providers';

import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: Readonly<Props>) {
  const { locale } = await params;
  if (!hasLocale(locale as TypeLocales)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className="roboto">
        <NextIntlClientProvider>
          <Providers>
            <RootLayoutContent>{children}</RootLayoutContent>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
