import { notFound } from "next/navigation";

import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";

import { TypeLocales } from "@/i18n/routing";
import { hasLocale } from "@/i18n/utils";
import Providers from "@/components/providers/Providers";

import "../globals.css";
import { getLocaleData } from "@/i18n/request";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: Readonly<Props>) {
  const { locale } = await params;
  if (!hasLocale(locale as TypeLocales)) {
    notFound();
  }
  const { messages } = await getLocaleData(locale);
  return (
    <html lang={locale}>
      <body className="roboto">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
