import type { Metadata } from "next";
import "../globals.css";

import Providers from "@/providers/Providers";
import RootLayoutContent from "@/components/layouts/RootLayoutContent";

import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: Readonly<Props>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className="roboto">
        <NextIntlClientProvider>
          <Providers>
            <RootLayoutContent>{children}</RootLayoutContent>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
